[project]
name = "starknet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "jinja2",
  "eth-hash",
  "pynacl",
  "libp2p==0.2.4",
]
